### ISSUE TITLE
Custom Training

### ISSUE THREAD

**Issue by ghost** [lawinsider/stanford-ner-docker#1]
Hi,

I just tried your greta container, and I was wondering how it could be easy to provide additional data about organizations from (https://github.com/datasets) with a rest endpoint.

Cheers,
Luc Michalski

**Comment by sadovnychyi** [comment]
As I understand you found out already that's it's better to use something like AIDA for this purpose. 
NER can only tell you that this thing is likely to be an organization, without any idea which one exactly.

**Comment by ghost** [comment]
AIDA is huge, and I was concerned by performances if you wanted to make some processing on the fly.

I subscribed to the AIDA mailing list. Will ask the question.

Thanks for your reply
